"use client";
import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-slate-950 text-slate-200">
      {/* Background Elements */}
      <div className="absolute inset-0 bg-slate-950">
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px]"></div>
        <div className="absolute top-0 right-0 left-0 -z-10 m-auto h-[310px] w-[310px] rounded-full bg-rose-500 opacity-20 blur-[100px]"></div>
        <div className="absolute right-0 bottom-0 -z-10 h-[310px] w-[310px] rounded-full bg-blue-500 opacity-20 blur-[100px]"></div>
      </div>

      {/* Hero Section */}
      <div className="relative border-b border-white/5 bg-slate-900/40 px-6 py-16 text-center backdrop-blur-sm md:py-24">
        <h1 className="font-anton mb-6 text-4xl text-white uppercase md:text-7xl">
          Terms of <span className="text-rose-500">Service</span>
        </h1>
        <p className="mx-auto max-w-2xl text-base text-slate-400 md:text-lg">
          Please read these terms carefully before participating in our
          tournaments.
        </p>
      </div>

      <div className="container mx-auto max-w-4xl px-4 py-8 md:py-16">
        <div className="space-y-10 rounded-3xl border border-white/5 bg-slate-900/40 p-6 backdrop-blur-md md:p-12">
          {/* Section 1: Introduction */}
          <section className="border-b border-white/5 pb-8 md:pb-10">
            <div className="mb-4 flex items-center gap-3 md:gap-4">
              <span className="flex h-8 w-8 items-center justify-center rounded-full bg-rose-500/10 text-sm font-bold text-rose-500">
                01
              </span>
              <h2 className="font-anton text-xl text-white uppercase md:text-2xl">
                Introduction
              </h2>
            </div>
            <div className="space-y-4 pl-11 text-sm leading-relaxed text-slate-400 md:pl-12 md:text-base">
              <p>
                This document is an electronic record in terms of Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes as amended by the Information Technology Act, 2000.
                This electronic record is generated by a computer system and
                does not require any physical or digital signatures.
              </p>
              <p>
                This document is published in accordance with the provisions of
                Rule 3 (1) of the Information Technology (Intermediaries
                guidelines) Rules, 2011 that require publishing the rules and
                regulations, privacy policy and Terms of Use for access or usage
                of domain name https://vrivalsarena.com ('Website'), including
                the related mobile site and mobile application (hereinafter
                referred to as 'Platform').
              </p>
              <p>
                The Platform is owned by <strong>VRivals Arena</strong> with its
                registered office at <strong>Krishna Apartment, Nigdi</strong>{" "}
                (hereinafter referred to as ‘Platform Owner’, 'we', 'us',
                'our').
              </p>
            </div>
          </section>

          {/* Section 2: Agreement to Terms */}
          <section className="border-b border-white/5 pb-8 md:pb-10">
            <div className="mb-4 flex items-center gap-3 md:gap-4">
              <span className="flex h-8 w-8 items-center justify-center rounded-full bg-rose-500/10 text-sm font-bold text-rose-500">
                02
              </span>
              <h2 className="font-anton text-xl text-white uppercase md:text-2xl">
                Agreement to Terms
              </h2>
            </div>
            <div className="space-y-4 pl-11 text-sm leading-relaxed text-slate-400 md:pl-12 md:text-base">
              <p>
                Your use of the Platform and services and tools are governed by
                the following terms and conditions (“Terms of Use”) as
                applicable to the Platform including the applicable policies
                which are incorporated herein by way of reference. If You
                transact on the Platform, You shall be subject to the policies
                that are applicable to the Platform for such transaction.
              </p>
              <p>
                ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES
                YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS
                OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE
                PROCEEDING.
              </p>
            </div>
          </section>

          {/* Section 3: Terms of Use */}
          <section className="border-b border-white/5 pb-8 md:pb-10">
            <div className="mb-4 flex items-center gap-3 md:gap-4">
              <span className="flex h-8 w-8 items-center justify-center rounded-full bg-rose-500/10 text-sm font-bold text-rose-500">
                03
              </span>
              <h2 className="font-anton text-xl text-white uppercase md:text-2xl">
                Terms of Use
              </h2>
            </div>
            <div className="space-y-4 pl-11 text-sm text-slate-400 md:pl-12 md:text-base">
              <p className="mb-2">
                The use of Platform and/or availing of our Services is subject
                to the following Terms of Use:
              </p>
              <ul className="grid gap-4">
                {[
                  "To access and use the Services, you agree to provide true, accurate and complete information.",
                  "Neither we nor any third parties provide any warranty or guarantee as to the accuracy of information offered on this website.",
                  "Your use of our Services is solely at your own risk and discretion.",
                  "The contents of the Platform (design, layout, look, graphics) are proprietary to us.",
                  "Unauthorized use of the Platform may lead to action against you as per applicable laws.",
                  "You agree to pay us the charges associated with availing the Services.",
                  "You agree not to use the Platform for any purpose that is unlawful or illegal.",
                  "We are not responsible for the content or policies of third-party websites linked on our Platform.",
                  "Initiating a transaction creates a legally binding contract with the Platform Owner.",
                  "You shall indemnify Platform Owner against any claims arising out of your breach of these Terms.",
                  "We are not liable for failure to perform obligations due to force majeure events.",
                  "These Terms regarding dispute resolution shall be governed by the laws of India.",
                  "All disputes shall be subject to the exclusive jurisdiction of the courts in Pune, India.",
                ].map((term, index) => (
                  <li
                    key={index}
                    className="flex items-start gap-3 rounded-lg border border-white/5 bg-slate-950/30 p-3 transition-colors hover:border-rose-500/20"
                  >
                    <span className="mt-1 text-rose-500">❖</span>
                    <span>{term}</span>
                  </li>
                ))}
              </ul>
            </div>
          </section>

          {/* Section 4: Contact Information */}
          <section>
            <div className="mb-4 flex items-center gap-3 md:gap-4">
              <span className="flex h-8 w-8 items-center justify-center rounded-full bg-rose-500/10 text-sm font-bold text-rose-500">
                04
              </span>
              <h2 className="font-anton text-xl text-white uppercase md:text-2xl">
                Contact Information
              </h2>
            </div>
            <div className="pl-0 md:pl-12">
              <div className="flex flex-col gap-6 rounded-2xl border border-white/10 bg-slate-950/50 p-6 md:flex-row">
                <div className="space-y-1">
                  <p className="text-xs font-bold text-slate-500 uppercase">
                    Entity
                  </p>
                  <p className="font-medium text-white">VRivals Arena</p>
                </div>
                <div className="space-y-1">
                  <p className="text-xs font-bold text-slate-500 uppercase">
                    Email
                  </p>
                  <a
                    href="mailto:support@vrivalsarena.com"
                    className="font-medium text-rose-400 transition-colors hover:text-rose-300"
                  >
                    support@vrivalsarena.com
                  </a>
                </div>
                <div className="space-y-1">
                  <p className="text-xs font-bold text-slate-500 uppercase">
                    Phone
                  </p>
                  <p className="font-medium text-white">9356832187</p>
                </div>
                <div className="space-y-1">
                  <p className="text-xs font-bold text-slate-500 uppercase">
                    Address
                  </p>
                  <p className="text-sm text-slate-300">
                    Krishna Apartment, Nigdi
                  </p>
                </div>
              </div>
            </div>
          </section>

          <div className="mt-8 border-t border-white/5 pt-8 text-center text-xs tracking-widest text-slate-600 uppercase">
            <p>
              Last Updated:{" "}
              {new Date().toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
